---
domains:
  # this is the for the Argo CD cli and web interface
  argo_cd: "argocd.selfhosting4dogs.com"

# this is for metallb
address_pool: "192.168.42.42-192.168.42.50"

# this is for cert-manager
email: "resident-internet-dog@selfhosting4dogs.com"

# this is for the external secrets operator, currently only works with gitlab
external_secrets:
  gitlab:
    access_token: "fjdkalhfjkdlahkhhajsfd"
    namespace: "default"
