---
domains:
  prometheus:
    prometheus: "prometheus.selfhosting4dogs.com"
    alert_manager: "alert-manager.selfhosting4dogs.com"
    grafana: "grafana.selfhosting4dogs.com"

address_pool: "192.168.42.42-192.168.42.50"
email: "resident-internet-dog@selfhosting4dogs.com"
