---
domains:
  argo_cd: "argocd.coolwebsitefordogs.com"
  argo_cd_grpc: "grpc.argocd.coolwebsitefordogs.com"

# these HAVE to be full CIDR notation
metallb_address_pool:
  - 192.168.90.01/32
  - 192.168.90.02/32
  - 192.168.90.03/32

email: "coolemailfordogs@onlydogs.com"

external_secrets:
  gitlab:
    access_token: "kjdfsk758934fkldsafds"
    namespace: "nextcloud"
