# metallb IPs used for DNS later
# (make sure they're not in use in your local router)
metallb_address_pool:
  # Example of required full CIDR notation: you have to fill this in
  - 192.168.90.01/32

# Used for letsencrypt-staging, to generate certs,
# needed only if you want to do real SSL testing
email: "coolemailfordogs@verygooddogs.net"

# FQDN to access your web interfaces (only needed for argocd)
domain:
  # your base domain for use with subdomains below
  base: "coolwebsitefordogs.com"
  # subdomain for Argo CD, so this would be argocd.coolwebsitefordogs.com
  argo_cd: "argocd"

# Use the external secrets provider with gitlab (only required for argocd)
external_secrets:
  gitlab:
    # going to be deprecated soon in favor of using another password manager
    # token from here: https://gitlab.com/-/profile/personal_access_tokens
    access_token: ""
    namespace: "nextcloud"

# optionally log to a file
log:
  # logging level, Options: debug, info, warn, error
  level: "info"
  # path of file to log to
  file: "./smol-k8s-lab.log"
