---
# the logging of smol-k8s-lab itself
log:
  ## path of file to log to if console logging is not desired
  # file: "./smol-k8s-log.log"
  # logging level, Options: debug, info, warn, error
  level: "info"

distribution:
  k3s:
    # enable k3s deployment
    enabled: true
    # if kubernetes.distribution set to k3s, you can add an array of extra
    # arguments to pass to the k3s install script
    extra_args: []
  kind:
    # enable kind deployment
    enabled: false
  k0s:
    # enable k0s deployment
    enabled: false

ingress-nginx:
  # enable or disable ingress-nginx
  enabled: true

cert-manager:
  # enable or disable cert-manager
  enabled: true
  # Used for letsencrypt-staging, to generate certs
  email: ""

metallb:
  # enable metallb which helps expose IP addresses for loadbalancers on metal
  enabled: true
  # metallb IPs used for DNS later (make sure they're not in use)
  address_pool:
  ## Example of required full CIDR notation
  # - 192.168.90.01/32

# Install ArgoCD to install other apps
argo_cd:
  enabled: true
  # FQDN domain for accessing the argoCD web interface
  domain: ""
  # set to "" for basic authentication via ArgoCD directly only keycloak has 
  # been tested so far
  identity_provider: "keycloak"

# allows you to specify a k8s secret with info like your hostnames
argo_cd_appset_secret_plugin:
  enabled: true

# keycloak is an IAM provider that you can use with ArgoCD for user/group
# management and oauth2. it can work with vouch to secure domains that
# otherwise wouldn't have authentication
keycloak:
  enabled: true
  # domain to use for keycloak
  domain: ""

kyverno:
  # enable kyverno, for k8s native policy management
  enabled: false
