---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: swfs-volume-data
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: swfs-master-data
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: swfs-filer-data
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
