base_screen:
  title: |
    Welcome to smol "K" eights lab. Press "C" to configure accessibility options.
  alt_title: |
    Welcome to smol "K" eights lab. Press tab. Then press "C" to configure accessibility options.
  description: |
    Description. There is an ascii text banner at the top of the screen that says smol "K" eights lab. Below there is one box. The box title is Create a new cluster with the name below. The box contains an input fiel for the name of your cluster with a submit button to the right that says sparkles emoji new cluster.
  alt_description: |
    Description. There is an ascii text banner at the top of the screen that says smol "K" eights lab. Below that are two boxes. Box one title is Select a row to modify or delete an existing cluster. Box one contains a data table with columns for Cluster, Distro, Version, and Platform for each cluster. Box two title is Create a new cluster with the name below. Box two contains an input fiel for the name of your cluster with a submit button to the right that says sparkles emoji new cluster.


distro_screen:
  title: |
    Kubernetes distribution config screen.


apps_screen:
  title: |
     Applications Configuration screen (now with more squid). Here you can select and configure Argo C.D. directory type apps.


config_screen:
  title: |
    Configure logging and password manager screen.


nodes_screen:
  title: |
    Add or delete nodes screen.


tui_config_screen:
  title: |
    Screen. Configure Terminal U.I. and Accessibility features.
  description: |
    Description. There are two boxes on the screen. Box one. Configure Terminal U.I. Box two. Configure Accessibility Features. Focus starts on Box one.


help_screen:
  title: Help Screen.
  description: |
    Use your mouse to click anything in the UI ✨ Or use the following key bindings: arrow keys for navigation within a widget, tab for navigation between widgets. For additional help, checkout https://small-hack.github.io/smol-k8s-lab.


confirm_screen:
  title: Confirm screen
  description: |
    This is the last step and screen to review your configuration.


cluster_modal_screen:
  title: What would you like to do with this cluster?
  description: |
    To quit this screen, press Q or B.
  alt_description: |
    Are you sure you want to delete this cluster?
