---
# https://github.com/bitnami/charts/tree/master/bitnami/postgresql
global:
  postgresql:
    auth:
      username: internetdog
      database: dogdb
      existingSecret: pgsql-credentials
      secretKeys:
        userPasswordKey: extraUserPassword
        adminPasswordKey: postgresPassword
volumePermissions:
  enabled: true
primary:
  pgHbaConfiguration: |-
    local all all trust
    host all all 127.0.0.1/32 md5
    host all internetdog 10.0.0.0/8 md5
  initdb:
    scripts:
      my_init_script.sql: |
        ALTER DATABASE dogdb OWNER TO internetdog;
        GRANT ALL PRIVILEGES ON DATABASE dogdb TO internetdog;
        GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO internetdog;
  persistence:
    enabled: true
    existingClaim: psql-pv-claim
