---
name: Python package build and publish
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          python_version: "3.12.0"
          pypi_token: ${{ secrets.DEPLOY_FROM_GITHUB_SMOL_K8S_LAB }}

      # not ready to do this until we have self-hosted runners
      # - name: Generate Sound Files
      #   run: |
      #       poetry run smol-tts -l en --tar
      #       poetry run smol-tts -l nl --tar

      # still figuring out how to make this work, so it is disabled for now
      # - name: Create an appimage for smol-k8s-lab for use with brew
      #   # see https://github.com/AppImageCommunity/pkg2appimage for more info
      #   run: |
      #       wget -c $(wget -q https://api.github.com/repos/AppImageCommunity/pkg2appimage/releases -O - | grep "pkg2appimage-.*-x86_64.AppImage" | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
      #       chmod +x ./pkg2appimage-*.AppImage
      #       ./pkg2appimage-*.AppImage .github/smol-k8s-lab-appimage.yaml

      - name: Create a Release on GitHub
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # files: |
          #     smol-k8s-lab.AppImage
          generate_release_notes: true
