---
name: Test smol-k8s-lab
on:
  pull_request:
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "docs/**"
jobs:
  smol_k8s_lab_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install smol-k8s-lab via poetry
        run: poetry install

      - name: Install Argo CD cli
        run: |
            curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
            sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
            rm argocd-linux-amd64

      - name: test smol-k8s-lab with kind
        run: |
            source .venv/bin/activate 
            smol-k8s-lab -c .github/smol_k8s_lab_config_kind.yaml

      - name: test smol-k8s-lab with k3s
        run: |
            source .venv/bin/activate 
            smol-k8s-lab -c .github/smol_k8s_lab_config_k3s.yaml
